[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm install -g pnpm@8", "pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["cd apps/backend && npx prisma generate"]

[start]
cmd = "cd apps/backend && npx tsx src/index.ts"
